export class TextInput extends inkCustomController {
  m_root?: wref;
  m_wrapper?: wref;
  m_measurer?: TextMeasurer;
  m_viewport?: Viewport;
  m_selection?: Selection;
  m_text?: TextFlow;
  m_caret?: Caret;
  m_isDisabled?: boolean;
  m_isHovered?: boolean;
  m_isFocused?: boolean;
  m_lastInputEvent?: inkKeyInputEvent;
  m_isHoldComplete?: boolean;
  m_holdTickCounter?: number;
  m_holdTickProxy?: inkAnimProxy;
  OnCreate(): void;
  OnInitialize(): void;
  CreateWidgets(): void;
  CreateAnimations(): void;
  InitializeLayout(): void;
  UpdateLayout(): void;
  ApplyDisabledState(): void;
  ApplyHoveredState(): void;
  ApplyFocusedState(): void;
  SetDisabledState(isDisabled: boolean): void;
  SetHoveredState(isHovered: boolean): void;
  SetFocusedState(isFocused: boolean): void;
  RegisterListeners(): void;
  RegisterHoldTick(): void;
  ProcessInputEvent(event: inkKeyInputEvent): void;
  TriggerChangeCallback(): void;
  OnInputKey(event: inkKeyInputEvent): void;
  OnHoldTick(anim: inkAnimProxy): void;
  OnReleaseKey(event: inkPointerEvent): void;
  OnTextMeasured(widget: inkWidget): void;
  OnHoverOver(event: inkPointerEvent): boolean;
  OnHoverOut(event: inkPointerEvent): boolean;
  OnFocusReceived(event: inkEvent): void;
  OnFocusLost(event: inkEvent): void;
  GetName(): string;
  SetName(name: string): void;
  GetText(): string;
  SetText(text: string): void;
  GetDefaultText(): string;
  SetDefaultText(text: string): void;
  GetMaxLength(): number;
  SetMaxLength(max: number): void;
  GetLetterCase(): textLetterCase;
  SetLetterCase(value: textLetterCase): void;
  GetWidth(): number;
  SetWidth(width: number): void;
  GetCaretPosition(): number;
  SetCaretPosition(position: number): void;
  IsHovered(): boolean;
  IsFocused(): boolean;
  IsDisabled(): boolean;
  IsEnabled(): boolean;
  SetDisabled(isDisabled: boolean): void;
  static Create(): TextInput;
}
