export class Selection extends inkCustomController {
  m_selection?: wref;
  m_startPosition?: number;
  m_endPosition?: number;
  m_maxPosition?: number;
  m_fontSize?: number;
  m_padSize?: number;
  OnCreate(): void;
  OnInitialize(): void;
  InitializeProps(): void;
  CreateWidgets(): void;
  InitializeLayout(): void;
  GetFontSize(): number;
  SetFontSize(fontSize: number): void;
  GetTintColor(): HDRColor;
  SetTintColor(color: HDRColor): void;
  GetOpacity(): number;
  SetOpacity(opacity: number): void;
  GetMaxPosition(): number;
  SetMaxPosition(max: number): void;
  GetStartPosition(): number;
  SetStartPosition(value: number): void;
  GetEndPosition(): number;
  SetEndPosition(value: number): void;
  SelectAll(): void;
  Clear(): void;
  GetLeftPosition(): number;
  GetRightPosition(): number;
  GetRange(): RectF;
  IsEmpty(): boolean;
  UpdateState(isFocused: boolean, selectedBounds: RectF): void;
  static Create(): Selection;
}
