export class TextFlow extends inkCustomController {
  m_text?: wref;
  m_value?: string;
  m_placeholder?: string;
  m_length?: number;
  m_maxLength?: number;
  m_charOffsets?: number[];
  m_tickProxy?: inkAnimProxy;
  OnCreate(): void;
  OnInitialize(): void;
  InitializeProps(): void;
  CreateWidgets(): void;
  InitializeOffsets(): void;
  ProcessInsertion(position: number, offset: number): void;
  ProcessDeletion(position: number): void;
  ProcessDeletion(start: number, end: number): void;
  UpdateFollowers(position: number, diff: number): void;
  UpdatePlaceholder(): void;
  GetText(): string;
  SetText(text: string): void;
  GetDefaultText(): string;
  SetDefaultText(text: string): void;
  GetLength(): number;
  GetMaxLength(): number;
  SetMaxLength(max: number): void;
  IsEmpty(): boolean;
  IsFull(): boolean;
  GetLetterCase(): textLetterCase;
  SetLetterCase(value: textLetterCase): void;
  GetFontSize(): number;
  SetFontSize(fontSize: number): void;
  GetCharOffset(position: number): number;
  SetCharOffset(position: number, offset: number): void;
  GetCharWidth(position: number): number;
  SetCharWidth(position: number, width: number): void;
  GetCharPosition(offset: number): number;
  GetCharRange(range: RectF): RectF;
  GetNextStop(current: number): number;
  GetPrevStop(current: number): number;
  InsertCharAt(position: number, char: string): void;
  InsertTextAt(position: number, text: string): void;
  DeleteCharAt(position: number): void;
  DeleteCharRange(start: number, end: number): void;
  GetDesiredSize(): { x: number; y: number };
  static Create(): TextFlow;
}
