export class audioDirectorSystemSettings extends audioAudioMetadata {
  combatVoManagerSettingsName?: string;
  singleConversationMinRepeatTime?: number;
  allConversationsMinRepeatTime?: number;
  maxVelocityMagnitudeToConsiderPlayerVehicleInactive?: number;
  maxVelocityMagnitudeToConsiderTrafficVehicleIdle?: number;
  playerInactiveMinTimeNeededToEngageMovingFaster?: number;
  vehEngageMovingFasterInterpolation?: audioVehicleEngageMovingFasterInterpolationData;
  playerBrakeEventCooldown?: number;
  trafficSpeedRC?: number;
  trafficAccelerationRC?: number;
  trafficRpmRC?: number;
  trafficSlipRatioSkidThreshold?: number;
  trafficHornSingleVehicleCooldown?: number;
  trafficHornAllVehiclesCooldown?: number;
  trafficHornMaxDistanceRangeToPlayer?: number;
  overHeadVisibilityMaxOcclusion?: number;
  overHeadVisibilityMaxObstruction?: number;
  conversationMixCooldown?: number;
  enemyPingCooldown?: number;
  idleTimeBeforeAllowingOwMusicChange?: number;
  drivingStreamingAmbientEmittersDistanceRolloff?: number;
  lowHealthStateMaxTime?: number;
  lowGearMaxTrafficSpeed?: number;
  lowGearAccelerationThreshold?: number;
  mediumGearMaxTrafficSpeed?: number;
  mediumGearAccelerationThreshold?: number;
  highGearAccelerationThreshold?: number;
}
