export class CloudAreaSettings extends IAreaSettings {
  cloudSunShadowFaloff?: CurveDataFloat;
  cloudSunScattering?: CurveDataFloat;
  cloudMoonScattering?: CurveDataFloat;
  cloudLightColor?: CurveDataHDRColor;
  cloudAmbientIntensity?: CurveDataFloat;
  cloudCirrusOpacity?: CurveDataFloat;
  cloudCirrusScale?: CurveDataFloat;
  cloudCirrusAltitude?: CurveDataFloat;
  cloudCirrusTexture?: ResourceRef;
  volWeatherTexture?: ResourceRef;
  volNoiseTexture?: ResourceRef;
  volHorizonCoverage?: number;
  volCoverage?: CurveDataFloat;
  volDensity?: CurveDataFloat;
  cloudsBottom?: number;
  cloudsTop?: number;
  rayStartOffset?: number;
  rayStartFalloff?: number;
  lightIntensity?: CurveDataFloat;
  reflectionProbeLightIntensity?: CurveDataFloat;
  shadowIntensity?: CurveDataFloat;
  worldShadowIntensity?: CurveDataFloat;
  ambientIntensity?: CurveDataFloat;
  ambientOutscatter?: CurveDataFloat;
  inScatter?: number;
  outScatter?: number;
  inVsOutScatter?: number;
  silverLining?: number;
  volCoverageWindInfluence?: number;
  volNoiseWindInfluence?: number;
  volDetailWindInfluence?: number;
  volDistantFogOpacity?: number;
  volCoverageOffset?: { x: number; y: number };
}
