export interface fxCompositionShaderParams {
  glitchParam?: number;
  glitchParam1?: number;
  health?: number;
  visionActiveTime?: number;
  uiFactor?: number;
  uiPassthroughFactor?: number;
  mainRenderFactor?: number;
  blurredRenderFactor?: number;
  backgroundTextureFactor?: number;
  backgroundBlurRadius?: number;
  sphericalDistPower?: { x: number; y: number };
  shadowDistance?: { x: number; y: number };
  shadowIntensity?: number;
  shadowRadius?: number;
  glowIntensity?: number;
  glowTresholdStart?: number;
  glowTresholdEnd?: number;
  glowBlurRadius?: number;
  vignetteStart?: number;
  vignetteEnd?: number;
  vignetteIntensity?: number;
  blurredRenderSaturation?: number;
  uiSaturation?: number;
  chromaticAberrationStrength?: number;
  uiLayer2Scale?: { x: number; y: number };
  uiLayer3Scale?: { x: number; y: number };
  uiLayer4Scale?: { x: number; y: number };
  uiLayer2Weight?: number;
  uiLayer3Weight?: number;
  uiLayer4Weight?: number;
}
