export interface gameMuppetUpperBodyState {
  currentWeapon?: ItemID;
  wantedWeapon?: ItemID;
  inProgressWeapon?: ItemID;
  logicWantedWeapon?: ItemID;
  equippingTransitionTime?: number;
  remainingShotTime?: number;
  timeTillNextShootSeconds?: number;
  isAimingDownSight?: boolean;
  currentWeaponAmmo?: number;
  currentWeaponAmmoCapacity?: number;
  isShooting?: boolean;
  weaponZoomLevel?: number;
  weaponAimFOV?: number;
  remainingReloadTime?: number;
  remainingReloadCooldownTime?: number;
  shotsMade?: number;
  isMeleeAttackInProgress?: boolean;
  meleeAttacksMade?: number;
  meleeAttackIndex?: number;
  remainingMeleeAttackDuration?: number;
  selectedConsumable?: ItemID;
  consumableInUse?: boolean;
  consumableEffectApplied?: boolean;
  consumableUseTimeStartup?: number;
  consumableUseTimeRecovery?: number;
  remainingQuickMeleeTime?: number;
  remainingQuickMeleeCooldownTime?: number;
}
