export abstract class CustomButton extends inkCustomController {
  m_root?: wref;
  m_label?: wref;
  m_useAnimations?: boolean;
  m_useSounds?: boolean;
  m_isDisabled?: boolean;
  m_isHovered?: boolean;
  m_isPressed?: boolean;
  OnCreate(): void;
  OnInitialize(): void;
  CreateWidgets(): void;
  CreateAnimations(): void;
  RegisterListeners(): void;
  ApplyDisabledState(): void;
  ApplyHoveredState(): void;
  ApplyPressedState(): void;
  SetDisabledState(isDisabled: boolean): void;
  SetHoveredState(isHovered: boolean): void;
  SetPressedState(isPressed: boolean): void;
  OnHoverOver(evt: inkPointerEvent): boolean;
  OnHoverOut(evt: inkPointerEvent): boolean;
  OnPress(evt: inkPointerEvent): boolean;
  OnRelease(evt: inkPointerEvent): boolean;
  GetName(): string;
  GetState(): inkEButtonState;
  GetText(): string;
  IsEnabled(): boolean;
  IsDisabled(): boolean;
  IsHovered(): boolean;
  IsPressed(): boolean;
  SetName(name: string): void;
  SetText(text: string): void;
  SetPosition(x: number, y: number): void;
  SetWidth(width: number): void;
  SetDisabled(isDisabled: boolean): void;
  ToggleAnimations(useAnimations: boolean): void;
  ToggleSounds(useSounds: boolean): void;
}
