export class LocalizationSystem extends ScriptableSystem {
  m_interfaceLanguage?: string;
  m_subtitleLanguage?: string;
  m_voiceLanguage?: string;
  m_playerGender?: PlayerGender;
  m_providers?: ModLocalizationProvider[];
  m_interfaceTranslationLanguage?: string;
  m_interfaceTranslationData?: inkHashMap;
  m_subtitleTranslationLanguage?: string;
  m_subtitleTranslationData?: inkHashMap;
  m_settingsWatcher?: LanguageSettingsWatcher;
  m_genderWatcher?: PlayerGenderWatcher;
  m_localeChanged?: boolean;
  m_genderChanged?: boolean;
  OnAttach(): void;
  OnDetach(): void;
  OnRegisterProviderRequest(request: RegisterProviderRequest): void;
  OnUpdateLocaleRequest(request: UpdateLocaleRequest): void;
  OnUpdateGenderRequest(request: UpdateGenderRequest): void;
  OnUpdateTranslationsRequest(request: UpdateTranslationsRequest): void;
  NotifyProviders(): void;
  UpdateLocale(): void;
  UpdateGender(): void;
  UpdateTranslations(): void;
  MergeTranslations(provider: ModLocalizationProvider): void;
  InvalidateTranslations(): void;
  CollectTranslationData(translations: inkHashMap, type: EntryType, language: string): void;
  FillTranslationData(translations: inkHashMap, provider: ModLocalizationProvider, type: EntryType, language: string): void;
  FillTranslationsFromPackage(translations: inkHashMap, package: ModLocalizationPackage, type: EntryType): void;
  GetTranslationFrom(translations: inkHashMap, key: string): string;
  GetText(key: string): string;
  GetSubtitle(key: string): string;
  GetInterfaceLanguage(): string;
  GetSubtitleLanguage(): string;
  GetVoiceLanguage(): string;
  GetPlayerGender(): PlayerGender;
  RegisterProvider(provider: ModLocalizationProvider): void;
  static GetInstance(game: GameInstance): LocalizationSystem;
}
