type UnwrapMpClass<T> = T extends { new (): infer U } ? U : T;
type CName = string;
type Handle<T = any> = T;
type WeakHandle<T = any> = T;
type ScriptRef<T = any> = T;
type NodeRef<T = any> = T;
type ResAsyncRef<T = any> = T;
type CurveData<T = any> = T;
type ResRef<T = any> = T;
type TweakDBID = string;
type CRUID = any;
type CGUID = any;
type Variant = any;
type LocalizationString = string;
type Uint16 = number;
type Uint8 = number;
type Int8 = number;
type Int16 = number;
type Int32 = number;
type DataBuffer = any;
type serializationDeferredDataBuffer = any;
type SharedDataBuffer = any;
type EditorObjectID = any;
type MessageResourcePath = any;
type MultiChannelCurve<T = any> = T;
