name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm env use --global 22

      - run: pnpm i

      - run: pnpm build

      - run: pnpm run biome:lint

      - run: pnpm run test
